---
exclude_paths:
  - "client/build/**"
  - "client/coverage/**"
  - "client/.angular/**"
  - "client/node_modules/**"
  - "client/.nyc_output/**"
  - "client/src/assets/**"
  - "client/*.config.*"
  - "client/cypress/**"
  - "README.md"
  - "run.sh"
  - "**/*.html"
  - "**/*.md"
  - "*.md"
  - "**/*.sh"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.map"
  - "**/__init__.py"
  - "**/eslint.config.js"
  - "docs/**"
  - ".github/**"
  - ".nyc_output/**"
  - "coverage/**"
  - "backend/**/doc/**"
  - "backend/**/docs/**"
  - "backend/**/test/**"
  - "backend/tests/**"
  - "backend/static/**"
  - "backend/workspace/**"
  - "backend/migrations/**"
  - "backend/configs/**"
  - "backend/orion/services/__init__.py"
  - "backend/orion/services/log_manager/log_controller.py"
  - "backend/orion/services/elastic_manager/elastic_request_generator.py"

engines:
  metric:
    config:
      languages:
        - "python"
        - "typescript"
        - "javascript"
  duplication:
    exclude_paths:
      - "client/build/**"
      - "client/coverage/**"
      - "client/.angular/**"
      - "client/node_modules/**"
      - "client/.nyc_output/**"
      - "client/src/assets/**"
      - "client/*.config.*"
      - "client/cypress/**"
      - "README.md"
      - "run.sh"
      - "**/*.html"
      - "**/__init__.py"
      - "**/eslint.config.js"
      - "docs/**"
      - ".github/**"
      - ".nyc_output/**"
      - "coverage/**"
      - "backend/**/doc/**"
      - "backend/**/docs/**"
      - "backend/**/test/**"
      - "backend/tests/**"
      - "backend/static/**"
      - "backend/workspace/**"
      - "backend/migrations/**"
      - "backend/configs/**"
      - "backend/orion/services/__init__.py"
      - "backend/orion/services/log_manager/log_controller.py"
      - "backend/orion/services/elastic_manager/elastic_request_generator.py"
