from orion.helper_manager.env_handler import env_handler


class REDIS_CONNECTIONS:
    S_DATABASE_IP = 'redis_server'
    S_DATABASE_PORT = 6379
    S_DATABASE_PASSWORD = env_handler.get_instance().env('REDIS_PASSWORD')


class REDIS_KEYS:
    INSIGHT_OLD_DAY = "INSIGHT_OLD_DAY_v2"
    INSIGHT_OLD_WEEK = "INSIGHT_OLD_WEEK_V2"
    INSIGHT_STAT = "INSIGHT_STAT_V2"
    GRAPH_INSIGHT_STAT = "GRAPH_INSIGHT_STAT_V2"
    APP_INSIGHT_KEY = "APP_INSIGHT_KEY_V2"
    COUNTRY_INSIGHT_KEY = "COUNTRY_INSIGHT_KEY"
    SATELLITE_ASSET_VERSION = "SATELLITE_ASSET_VERSION"


class REDIS_COMMANDS:
    S_SET_BOOL = 1
    S_GET_BOOL = 2
    S_SET_INT = 3
    S_GET_INT = 4
    S_SET_STRING = 5
    S_GET_STRING = 6
    S_SET_LIST = 7
    S_GET_LIST = 8
    S_GET_KEYS = 9
    S_GET_FLOAT = 10
    S_SET_FLOAT = 11
    S_FLUSH_ALL = 12
    S_ACQUIRE_LOCK = 13
    S_RELEASE_LOCK = 14
    S_DELETE_KEY = 15
