import { ReportFeedbackModel } from '../../../../../shared/partials/report-interactions/models/report-feedback.model';
import { ArtifactReportOption, Case, CaseAnalyst, CaseArtifact, CaseArtifactFile, CaseClosure, CaseCommunication, CaseEntity, CaseLink, CaseTask } from '../case.model';

export type CaseDetailsEditSection = 'caseDetails' | 'primaryEntity' | 'relatedEntities' | 'artifacts' | 'tasks' | 'linkedCases' | 'communications';

export abstract class CaseDetailsStore {
  abstract caseData: Case | null;
  abstract editedCase: Case | null;
  abstract isEditing: boolean;
  abstract activeEditSection: CaseDetailsEditSection | null;
  abstract isAddingRelatedEntity: boolean;
  abstract isAddingArtifact: boolean;
  abstract isAddingTask: boolean;
  abstract isAddingLinkedCase: boolean;
  abstract isAddingCommunication: boolean;
  abstract isClosingCase: boolean;
  abstract newRelatedEntity: CaseEntity | null;
  abstract newArtifact: CaseArtifact | null;
  abstract newTask: CaseTask | null;
  abstract newLinkedCase: CaseLink | null;
  abstract newCommunication: CaseCommunication | null;
  abstract newClosure: CaseClosure | null;
  abstract analysts: CaseAnalyst[];
  abstract accessibleCases: Case[];
  abstract get editablePrimaryEntity(): CaseEntity | null;
  abstract isCommentSaving: boolean;
  abstract isShareCreating: boolean;
  abstract isShareRevoking: boolean;
  abstract isPdfExporting: boolean;
  abstract isArchivingCase: boolean;
  abstract commentErrorMessage: string;

  abstract canManageCases(): boolean;
  abstract canUnarchiveCases(): boolean;
  abstract canEditTasksAndComments(): boolean;

  abstract enableEditing(section: CaseDetailsEditSection): void;
  abstract cancelEditing(): void;
  abstract saveCaseDetails(): void;
  abstract savePrimaryEntity(): void;
  abstract exportPdf(): void;
  abstract openArchiveConfirmation(): void;
  abstract openUnarchiveConfirmation(): void;
  abstract openShareConfirmation(): void;
  abstract openRevokeShareConfirmation(): void;
  abstract getCaseCommentsFeedback(): ReportFeedbackModel;
  abstract saveCaseComment(body: string): void;
  abstract openAddRelatedEntity(): void;
  abstract removeRelatedEntity(index: number): void;
  abstract saveRelatedEntities(): void;
  abstract saveNewRelatedEntity(): void;
  abstract openAddArtifact(): void;
  abstract saveArtifacts(): void;
  abstract removeArtifact(index: number): void;
  abstract uploadArtifactFiles(artifact: CaseArtifact, fileInput: HTMLInputElement): void;
  abstract downloadArtifactFile(artifact: CaseArtifact, fileId: string): void;
  abstract deleteArtifactFile(artifact: CaseArtifact, fileId: string): void;
  abstract setPendingNewArtifactFiles(fileInput: HTMLInputElement): void;
  abstract getPendingNewArtifactFileNameRows(): string[];
  abstract saveNewArtifact(): void;
  abstract openAddTask(): void;
  abstract saveTasks(): void;
  abstract removeTask(index: number): void;
  abstract saveNewTask(): void;
  abstract openAddLinkedCase(): void;
  abstract saveLinkedCases(): void;
  abstract removeLinkedCase(index: number): void;
  abstract saveNewLinkedCase(): void;
  abstract goToLinkedCase(caseId: string): void;
  abstract openAddCommunication(): void;
  abstract saveNewCommunication(): void;
  abstract saveCommunication(communication: CaseCommunication): void;
  abstract removeCommunication(communicationId: string): void;
  abstract openCommunication(communication: CaseCommunication): void;
  abstract isCommunicationBusy(communication: CaseCommunication): boolean;
  abstract openCloseCase(): void;
  abstract openEditClosure(): void;
  abstract saveClosure(): void;
  abstract cancelSectionMode(): void;
  abstract loadArtifactReports(source: string, q?: string): void;
  abstract searchArtifactReports(source: string, q: string): void;
  abstract scheduleArtifactReportSearch(artifact: CaseArtifact): void;
  abstract selectArtifactReport(artifact: CaseArtifact, report: ArtifactReportOption): void;
  abstract clearArtifactReportSelection(artifact: CaseArtifact): void;
  abstract artifactReports: ArtifactReportOption[];
  abstract isArtifactReportsLoading: boolean;
  abstract artifactReportSearchText: string;
  abstract isArtifactReportDropdownOpen: boolean;
  abstract viewArtifactReport(artifact: CaseArtifact): void;
  abstract verifyArtifactFile(artifact: CaseArtifact, fileId: string): void;
  abstract isArtifactFileIntegrityFailed(artifactFile: CaseArtifactFile): boolean;
  abstract canAddTasks(): boolean;
  abstract canEditTask(task?: CaseTask | null): boolean;
  abstract canEditFullTask(): boolean;
}
